import { addDays, formatDocNumber, todayISO } from "@/lib/calc";
import type {
  AttendanceRecord,
  CompanySettings,
  Customer,
  DocumentKind,
  InventoryItem,
  Invoice,
  Quotation,
  SalesOrder,
  ServiceJob,
} from "@/types";

// Demo data is generated relative to "today" so the dashboard always looks current.

export const defaultSettings: CompanySettings = {
  name: "Singapore Tech Solutions Pte Ltd",
  uen: "201912345K",
  gstRegNo: "M2-0123456-7",
  address: "123 Marina Bay Drive, #08-01\nSingapore 018956",
  phone: "+65 6123 4567",
  email: "accounts@stechsolutions.com.sg",
  bankDetails: "DBS Bank · Acc 012-345678-9 · PayNow UEN 201912345K",
  gstRate: 9,
  paymentTermsDays: 30,
  quotationValidityDays: 30,
  defaultLabourRate: 85,
  prefixes: { quotation: "QT", salesOrder: "SO", invoice: "INV", serviceJob: "JOB" },
  technicians: ["Alex Lim", "Sarah Tan", "David Wong", "Mary Chen"],
  quotationTerms:
    "Prices quoted in SGD. 50% deposit upon confirmation, balance upon completion. Warranty: 12 months on parts and workmanship.",
};

export interface SeedData {
  customers: Customer[];
  inventory: InventoryItem[];
  jobs: ServiceJob[];
  attendance: AttendanceRecord[];
  quotations: Quotation[];
  salesOrders: SalesOrder[];
  invoices: Invoice[];
  counters: Record<DocumentKind, number>;
}

export function buildSeed(now: Date = new Date()): SeedData {
  const today = todayISO(now);
  const year = now.getFullYear();
  const day = (offset: number) => addDays(today, offset);
  const at = (offsetDays: number, time: string) => new Date(`${day(offsetDays)}T${time}:00`).toISOString();
  const num = (kind: DocumentKind, seq: number) => formatDocNumber(defaultSettings.prefixes[kind], year, seq);

  const customers: Customer[] = [
    {
      id: "cus-mbs",
      name: "Marina Bay Sands Pte Ltd",
      contactPerson: "Rachel Ng",
      email: "facilities@marinabaysands.example",
      phone: "+65 6688 8868",
      billingAddress: "10 Bayfront Avenue\nSingapore 018956",
      uen: "200601234D",
      createdAt: at(-120, "10:00"),
    },
    {
      id: "cus-raffles",
      name: "Raffles Hotel Singapore",
      contactPerson: "Daniel Koh",
      email: "engineering@raffles.example",
      phone: "+65 6337 1886",
      billingAddress: "1 Beach Road\nSingapore 189673",
      uen: "198901234N",
      createdAt: at(-90, "11:30"),
    },
    {
      id: "cus-changi",
      name: "Changi Airport Terminal 3",
      contactPerson: "Priya Raman",
      email: "t3-ops@changiairport.example",
      phone: "+65 6595 6868",
      billingAddress: "65 Airport Boulevard\nSingapore 819663",
      uen: "200904567G",
      createdAt: at(-60, "09:15"),
    },
    {
      id: "cus-np",
      name: "Ngee Ann Polytechnic",
      contactPerson: "Mr. Lee Wei Ming",
      email: "procurement@np.example",
      phone: "+65 6466 6555",
      billingAddress: "535 Clementi Road\nSingapore 599489",
      uen: "T08GB0032G",
      createdAt: at(-30, "14:00"),
    },
  ];

  const inventory: InventoryItem[] = [
    {
      id: "inv-cat6",
      sku: "NET-CAT6-100",
      name: "Network Cable CAT6 (100m)",
      category: "Networking",
      brand: "Schneider",
      model: "SC-CAT6-100M",
      serialNumber: "SN20240001",
      location: "Warehouse A - Shelf 1",
      currentStock: 150,
      minStock: 20,
      unitCost: 25.5,
      unitPrice: 42,
      assignedTo: null,
      lastUpdated: day(-8),
    },
    {
      id: "inv-led12",
      sku: "LGT-LED-12W",
      name: "LED Bulb 12W",
      category: "Lighting",
      brand: "Philips",
      model: "PH-LED-12W",
      serialNumber: "SN20240002",
      location: "Warehouse B - Shelf 3",
      currentStock: 15,
      minStock: 25,
      unitCost: 8.9,
      unitPrice: 15.9,
      assignedTo: null,
      lastUpdated: day(-9),
    },
    {
      id: "inv-cam4mp",
      sku: "SEC-CAM-4MP",
      name: "Security Camera 4MP",
      category: "Security",
      brand: "Hikvision",
      model: "HK-CAM-4MP",
      serialNumber: "SN20240003",
      location: "Warehouse A - Shelf 4",
      currentStock: 12,
      minStock: 5,
      unitCost: 185,
      unitPrice: 289,
      assignedTo: null,
      lastUpdated: day(-10),
    },
    {
      id: "inv-sw24",
      sku: "NET-SW-24P",
      name: "Ethernet Switch 24-Port",
      category: "Networking",
      brand: "Cisco",
      model: "CS-SW-24P",
      serialNumber: "SN20240004",
      location: "Warehouse A - Shelf 2",
      currentStock: 8,
      minStock: 3,
      unitCost: 450,
      unitPrice: 690,
      assignedTo: null,
      lastUpdated: day(-7),
    },
    {
      id: "inv-filter",
      sku: "HVAC-FLT-M8",
      name: "HVAC Air Filter MERV 8",
      category: "HVAC",
      brand: "3M",
      model: "FLT-M8-2020",
      serialNumber: "SN20240005",
      location: "Warehouse B - Shelf 1",
      currentStock: 40,
      minStock: 10,
      unitCost: 11.25,
      unitPrice: 22,
      assignedTo: null,
      lastUpdated: day(-5),
    },
    {
      id: "inv-nvr",
      sku: "SEC-NVR-16",
      name: "NVR 16-Channel",
      category: "Security",
      brand: "Hikvision",
      model: "DS-7616NI",
      serialNumber: "SN20240006",
      location: "Marina Bay Site",
      currentStock: 1,
      minStock: 2,
      unitCost: 620,
      unitPrice: 880,
      assignedTo: "Tech Team A",
      lastUpdated: day(-3),
    },
  ];

  const jobs: ServiceJob[] = [
    {
      id: "job-1",
      jobNumber: num("serviceJob", 1),
      customerId: "cus-mbs",
      customer: "Marina Bay Sands Pte Ltd",
      site: "Tower 1 - Level 55",
      serviceType: "Preventive Maintenance",
      technician: "Alex Lim",
      dateScheduled: day(-6),
      timeScheduled: "09:00",
      status: "Completed",
      priority: "Medium",
      description: "HVAC system quarterly maintenance",
      partsUsed: [{ itemId: "inv-filter", item: "HVAC Air Filter MERV 8", quantity: 4, cost: 22 }],
      labourRate: 85,
      customerSignature: true,
      photos: 3,
      notes: "System running optimally. Next service due in 3 months.",
      invoiceId: null,
      partsDeducted: true,
    },
    {
      id: "job-2",
      jobNumber: num("serviceJob", 2),
      customerId: "cus-raffles",
      customer: "Raffles Hotel Singapore",
      site: "Main Lobby",
      serviceType: "Corrective Maintenance",
      technician: "Sarah Tan",
      dateScheduled: today,
      timeScheduled: "08:30",
      status: "In Progress",
      priority: "High",
      description: "Network connectivity issues at front desk",
      partsUsed: [
        { itemId: "inv-cat6", item: "Network Cable CAT6 (100m)", quantity: 1, cost: 42 },
        { itemId: "inv-sw24", item: "Ethernet Switch 24-Port", quantity: 1, cost: 690 },
      ],
      labourRate: 85,
      customerSignature: false,
      photos: 1,
      notes: "Replaced faulty switch. Testing in progress.",
      invoiceId: null,
      partsDeducted: false,
    },
    {
      id: "job-3",
      jobNumber: num("serviceJob", 3),
      customerId: "cus-changi",
      customer: "Changi Airport Terminal 3",
      site: "Departure Hall B",
      serviceType: "Installation",
      technician: "David Wong",
      dateScheduled: day(2),
      timeScheduled: "08:00",
      status: "Scheduled",
      priority: "Medium",
      description: "Security camera installation - 8 units",
      partsUsed: [],
      labourRate: 85,
      customerSignature: false,
      photos: 0,
      notes: "Pre-installation site survey completed.",
      invoiceId: null,
      partsDeducted: false,
    },
  ];

  const attendance: AttendanceRecord[] = [
    {
      id: "att-1",
      jobId: "job-1",
      technician: "Alex Lim",
      checkIn: at(-6, "09:05"),
      checkOut: at(-6, "12:20"),
      checkInLocation: { lat: 1.2834, lng: 103.8607 },
      checkOutLocation: { lat: 1.2834, lng: 103.8607 },
      notes: "Filters replaced, coils cleaned.",
    },
    {
      id: "att-2",
      jobId: "job-2",
      technician: "Sarah Tan",
      checkIn: at(0, "08:40"),
      checkOut: null,
      checkInLocation: { lat: 1.2949, lng: 103.8545 },
      checkOutLocation: null,
      notes: "",
    },
  ];

  const quoteLines = [
    { id: "l1", itemId: "inv-cam4mp", description: "Security Camera 4MP (Hikvision HK-CAM-4MP)", quantity: 8, unitPrice: 289, discountPct: 5 },
    { id: "l2", itemId: "inv-nvr", description: "NVR 16-Channel (DS-7616NI)", quantity: 1, unitPrice: 880, discountPct: 0 },
    { id: "l3", itemId: null, description: "Installation & commissioning (lump sum)", quantity: 1, unitPrice: 1200, discountPct: 0 },
  ];

  const quotations: Quotation[] = [
    {
      id: "qt-1",
      number: num("quotation", 1),
      customerId: "cus-changi",
      date: day(-14),
      validUntil: day(16),
      status: "Accepted",
      lines: quoteLines,
      gstRate: 9,
      notes: "Includes cabling within 30m per camera.",
      reference: "T3 CCTV Upgrade",
      terms: defaultSettings.quotationTerms,
      salesOrderId: "so-1",
      invoiceId: null,
    },
    {
      id: "qt-2",
      number: num("quotation", 2),
      customerId: "cus-np",
      date: day(-3),
      validUntil: day(27),
      status: "Sent",
      lines: [
        { id: "l1", itemId: "inv-led12", description: "LED Bulb 12W (Philips)", quantity: 200, unitPrice: 15.9, discountPct: 10 },
        { id: "l2", itemId: null, description: "Replacement labour - Block 22 classrooms", quantity: 16, unitPrice: 85, discountPct: 0 },
      ],
      gstRate: 9,
      notes: "",
      reference: "Lighting retrofit",
      terms: defaultSettings.quotationTerms,
      salesOrderId: null,
      invoiceId: null,
    },
    {
      id: "qt-3",
      number: num("quotation", 3),
      customerId: "cus-mbs",
      date: day(-1),
      validUntil: day(29),
      status: "Draft",
      lines: [{ id: "l1", itemId: "inv-sw24", description: "Ethernet Switch 24-Port (Cisco)", quantity: 4, unitPrice: 690, discountPct: 0 }],
      gstRate: 9,
      notes: "",
      reference: "Tower 2 network refresh",
      terms: defaultSettings.quotationTerms,
      salesOrderId: null,
      invoiceId: null,
    },
  ];

  const salesOrders: SalesOrder[] = [
    {
      id: "so-1",
      number: num("salesOrder", 1),
      customerId: "cus-changi",
      date: day(-10),
      deliveryDate: day(2),
      status: "Confirmed",
      lines: quoteLines,
      gstRate: 9,
      notes: "",
      reference: "T3 CCTV Upgrade",
      quotationId: "qt-1",
      invoiceId: null,
      fulfilledAt: null,
    },
  ];

  const invoices: Invoice[] = [
    {
      id: "inv-1",
      number: num("invoice", 1),
      customerId: "cus-mbs",
      date: day(-40),
      dueDate: day(-10),
      status: "Issued",
      lines: [{ id: "l1", itemId: null, description: "Annual HVAC maintenance contract - Q2", quantity: 1, unitPrice: 4800, discountPct: 0 }],
      gstRate: 9,
      notes: "",
      reference: "Contract MBS-HVAC-24",
      payments: [{ id: "p1", date: day(-12), amount: 5232, method: "Bank Transfer", reference: "DBS-TRX-88421" }],
      source: null,
    },
    {
      id: "inv-2",
      number: num("invoice", 2),
      customerId: "cus-raffles",
      date: day(-45),
      dueDate: day(-15),
      status: "Issued",
      lines: [
        { id: "l1", itemId: null, description: "Emergency callout - chiller fault", quantity: 1, unitPrice: 350, discountPct: 0 },
        { id: "l2", itemId: null, description: "Labour (hours)", quantity: 5, unitPrice: 85, discountPct: 0 },
      ],
      gstRate: 9,
      notes: "",
      reference: "",
      payments: [],
      source: null,
    },
    {
      id: "inv-3",
      number: num("invoice", 3),
      customerId: "cus-np",
      date: day(-5),
      dueDate: day(25),
      status: "Issued",
      lines: [{ id: "l1", itemId: "inv-cat6", description: "Network Cable CAT6 (100m)", quantity: 20, unitPrice: 42, discountPct: 0 }],
      gstRate: 9,
      notes: "",
      reference: "PO-NP-7781",
      payments: [{ id: "p1", date: day(-1), amount: 400, method: "PayNow", reference: "PN-55120" }],
      source: null,
    },
  ];

  return {
    customers,
    inventory,
    jobs,
    attendance,
    quotations,
    salesOrders,
    invoices,
    counters: { quotation: 3, salesOrder: 1, invoice: 3, serviceJob: 3 },
  };
}
